DEVICE_PATH := device/lenovo/TB7104F

# Architecture
TARGET_ARCH := arm
TARGET_CPU_VARIANT := generic
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_SMP := true

# Kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/zImage

# Storage / Partitions (Matches TB-7104F Scatter)
BOARD_RECOVERY_PARTITION_SIZE := 16777216
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_HAS_LARGE_FILESYSTEM := true

# Performance & RAM Tricks
BOARD_HAS_LOW_RAM := true
TW_DEFAULT_BRIGHTNESS := 100
TW_MAX_BRIGHTNESS := 255
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_NO_REBOOT_RECOVERY := true
